/** @type {import('./$types').PageLoad} */
import getDirectusInstance from '$lib/directus';
import { readItems } from '@directus/sdk';

export async function load({ fetch }) {
    // Haal de directus instance op
	const directus = getDirectusInstance(fetch);

	try {
        /*
            ?- 'directus':
                This is your Directus SDK instance, which you initialized earlier with createDirectus. (src/lib/directus.js)
            ?- '.request':
                This sends the request to the Directus API using the configuration generated by readItems.
            ?- 'readItems':
                This generates a configuration object that describes a GET request to retrieve items from the person collection in your Directus database, including any specified query parameters (like fields and sort).
        */

		const people = await directus.request(readItems('person', {
			fields: ['id', 'name', 'bio'],  // Dit kan je aanpassen als je nog meer informatie hier wilt hebben
			sort: ['id'],                  // Sorteer op naam of id
		}));

		return {
			people
		};
	} catch (error) {
		console.error('Personen kunnen niet geladen worden: ', error);
		return {
			people: [] // Stuur een lege array terug als er een error is
		};
	}
}
